/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BaseboardMenu: typeof import('./src/components/BaseboardMenu.vue')['default']
    BaseboradMenu: typeof import('./src/components/BaseboradMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeComponent: typeof import('./src/components/Menu.vue')['default']
    MapPlaceholder: typeof import('./src/components/MapPlaceholder.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    PickupTimeModal: typeof import('./src/components/PickupTimeModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
